import React from 'react';
import { View, Text, Pressable, StyleSheet, ScrollView } from 'react-native';
import { styles as b, COLORS } from '../theme';

export default function HomeScreen({ navigation }) {
  return <ScrollView contentContainerStyle={b.content}><Text style={s.greeting}>Welcome to JustSPAI 👋</Text><Text style={b.title}>Travel safe. Travel smart.</Text><Text style={b.subtitle}>Discover trusted people, plan better trips and stay connected.</Text>
    <View style={s.hero}><Text style={s.heroTitle}>Find your travel companion</Text><Text style={s.heroText}>Match by destination, dates, budget, language and interests.</Text><Pressable style={s.heroButton} onPress={() => navigation.navigate('SearchScreen')}><Text style={s.heroButtonText}>Find Matches</Text></Pressable></View>
    <Pressable style={s.premium} onPress={() => navigation.navigate('SubscriptionScreen')}><View><Text style={s.premiumTitle}>✨ JustSPAI Premium</Text><Text style={s.premiumText}>7-day trial • ₹99/month • ₹649/year</Text></View><Text style={s.arrow}>›</Text></Pressable>
    <View style={s.grid}><Pressable style={s.tile} onPress={() => navigation.navigate('ProfileScreen')}><Text style={s.icon}>👤</Text><Text style={s.tileTitle}>Profile</Text><Text style={s.tileText}>Manage your preferences</Text></Pressable><Pressable style={s.tile} onPress={() => navigation.navigate('ChatScreen')}><Text style={s.icon}>💬</Text><Text style={s.tileTitle}>Messages</Text><Text style={s.tileText}>Chat with companions</Text></Pressable><Pressable style={s.tile} onPress={() => navigation.navigate('TripPlanningScreen')}><Text style={s.icon}>🗺️</Text><Text style={s.tileTitle}>Trips</Text><Text style={s.tileText}>Plan together</Text></Pressable><Pressable style={s.tile} onPress={() => navigation.navigate('SafetyScreen')}><Text style={s.icon}>🛡️</Text><Text style={s.tileTitle}>Safety</Text><Text style={s.tileText}>SOS & trust tools</Text></Pressable></View></ScrollView>;
}

const s = StyleSheet.create({ greeting: { fontWeight: '700', color: COLORS.muted, marginBottom: 6 }, hero: { backgroundColor: COLORS.navy, borderRadius: 22, padding: 22, marginTop: 24, marginBottom: 14 }, heroTitle: { fontSize: 23, fontWeight: '900', color: '#fff' }, heroText: { color: '#D9E2EC', lineHeight: 21, marginTop: 8 }, heroButton: { backgroundColor: '#fff', padding: 13, borderRadius: 11, alignItems: 'center', marginTop: 18 }, heroButtonText: { color: COLORS.navy, fontWeight: '800' }, premium: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#F0F6FF', borderWidth: 1, borderColor: '#C9DBEF', borderRadius: 17, padding: 16, marginBottom: 20 }, premiumTitle: { color: COLORS.navy, fontWeight: '900', fontSize: 16 }, premiumText: { color: COLORS.muted, marginTop: 4, fontSize: 12 }, arrow: { fontSize: 28, color: COLORS.navy }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, tile: { width: '47%', backgroundColor: COLORS.light, borderRadius: 17, padding: 16, borderWidth: 1, borderColor: '#E7EEF5' }, icon: { fontSize: 26, marginBottom: 10 }, tileTitle: { fontWeight: '800', fontSize: 16, color: COLORS.navy }, tileText: { color: COLORS.muted, fontSize: 12, marginTop: 4 } });
