import React, { useState } from 'react';
import { View, Text, TextInput, Pressable, ScrollView, StyleSheet, Alert } from 'react-native';
import { styles as base, COLORS } from '../theme';
const interests=['Adventure','Food','Nature','Photography','Culture','Backpacking'];
export default function ProfileScreen({navigation}){const [selected,setSelected]=useState([]);const [verified,setVerified]=useState(false);const [form,setForm]=useState({name:'',age:'',location:'',bio:'',budget:'',destinations:''});const set=(k,v)=>setForm({...form,[k]:v});return <ScrollView contentContainerStyle={base.content}>
<Text style={base.title}>Build your profile</Text><Text style={base.subtitle}>Tell travellers what makes you a great companion.</Text>
{[['name','Name'],['age','Age'],['location','Location'],['destinations','Preferred destinations'],['budget','Travel budget']].map(([k,p])=><TextInput key={k} style={base.input} placeholder={p} value={form[k]} onChangeText={v=>set(k,v)} />)}
<TextInput style={[base.input,{height:90,textAlignVertical:'top'}]} placeholder="Bio" multiline value={form.bio} onChangeText={v=>set('bio',v)}/>
<Text style={s.label}>Interests</Text><View style={s.tags}>{interests.map(x=><Pressable key={x} onPress={()=>setSelected(selected.includes(x)?selected.filter(i=>i!==x):[...selected,x])} style={[s.tag,selected.includes(x)&&s.active]}><Text style={selected.includes(x)&&s.activeText}>{x}</Text></Pressable>)}</View>
<View style={base.card}><Text style={s.verifyTitle}>Identity Verification</Text><Text style={base.subtitle}>Build trust with a verification badge. Connect a social profile or submit verification through the secure verification flow.</Text><Pressable style={s.verify} onPress={()=>{setVerified(true);Alert.alert('Verification','Verification request marked as submitted.')}}><Text style={s.verifyText}>{verified?'✓ Verification submitted':'Start verification'}</Text></Pressable></View>
<Pressable style={base.button} onPress={()=>navigation.navigate('SearchScreen')}><Text style={base.buttonText}>Save & Find Buddies</Text></Pressable></ScrollView>}
const s=StyleSheet.create({label:{fontWeight:'800',color:COLORS.text,marginBottom:10},tags:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:18},tag:{paddingHorizontal:14,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:COLORS.border,backgroundColor:'#fff'},active:{backgroundColor:COLORS.navy,borderColor:COLORS.navy},activeText:{color:'#fff'},verifyTitle:{fontSize:17,fontWeight:'800',color:COLORS.navy,marginBottom:6},verify:{marginTop:14,borderWidth:1,borderColor:COLORS.navy,padding:12,borderRadius:10,alignItems:'center'},verifyText:{fontWeight:'700',color:COLORS.navy}});
